---
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r, echo=FALSE, warning=FALSE}
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
```



# Applied exercises

\noindent
3. Please refer to the NYC flight data `nycflights13` that has been discussed in the lecture notes and whose manual can be found at https://cran.r-project.org/web/packages/nycflights13/index.html. We will use `flights`, a tibble from `nycflights13`.


Select from `flights` observations that are for 3 `carrier` "UA", "AA" or "DL", for `month` 7 and 2, and for 4 features `dep_delay`, `arr_delay`, `distance` and `air_time`. Let us try to see if we can use the 4 features to identify if an observation belongs a specific carrier or a specific month. The following tasks and questions are based on the extracted observations. Note that you need to remove `na`'s from the extracted observations.

```{R 3}
library(dplyr)
library(ggplot2)
library(scales)

data = nycflights13::flights
data1 = nycflights13::flights

data = data %>% filter(month %in% c(2,7) & carrier %in% c("UA", "AA", "DL") & !is.na(arr_delay)& !is.na(dep_delay) & !is.na(air_time) & !is.na(distance)) %>% select(dep_delay, air_time, distance, arr_delay, carrier, month)

data1 = data1 %>% filter(month %in% c(2,7) & carrier %in% c("UA", "AA", "DL") & !is.na(arr_delay)& !is.na(dep_delay) & !is.na(air_time) & !is.na(distance)) %>% select(dep_delay, air_time, distance, arr_delay, carrier, month)

head(data)

```

3.1) Apply K-means with $K=2$ and $3$ respectively but all with `set.seed(1)` and `nstart=20`. For $K=3$, provide visualization of the clustering results based on true clusters given by `carrier`, whereas for $K=2$, provide visualization of the clustering results based on true clusters given by `month`. Summarize your findings based on the clustering results. You can use the same visualization scheme that is provided by Example 2 in "LectureNotes3_notes.pdf". Try visualization based on different sets of 2 features if your visualization has overlayed points.
```{R 3.1}
set.seed(1)

km.out=kmeans(data[,1:4],3,nstart=20)
data$cluster=factor(km.out$cluster)
p = ggplot(data,aes(data$dep_delay,data$arr_delay))+
  geom_point(aes(shape= data$carrier,color=cluster))+   theme_bw()+ggtitle("3-means clustering via 4 features")
p

```

```{R 3.1.2}
set.seed(1)
km.out=kmeans(data[,1:4],2,nstart=20)
data$cluster=factor(km.out$cluster)
data$month = as.factor(data$month)
p2 = ggplot(data,aes(data$dep_delay,data$arr_delay))+
  geom_point(aes(shape= data$month,color=cluster))+   theme_bw()+ggtitle("2-means clustering via 4 features")
p2

```

```{R 3.1.3}

set.seed(1)

km.out=kmeans(data[,1:2],3,nstart=20)
data$cluster=factor(km.out$cluster)
p3 = ggplot(data,aes(data$dep_delay,data$air_time))+
  geom_point(aes(shape= data$carrier,color=cluster))+   theme_bw()+ggtitle("3-means clustering via 2 features")
p3

km.out=kmeans(data[,c(1,3)],3,nstart=20)
data$cluster=factor(km.out$cluster)
p4 = ggplot(data,aes(data$dep_delay, data$distance))+
  geom_point(aes(shape= data$carrier,color=cluster))+   theme_bw()+ggtitle("3-means clustering via 2 features")
p4

km.out=kmeans(data[,c(1,4)],3,nstart=20)
data$cluster=factor(km.out$cluster)
p5 = ggplot(data,aes(data$dep_delay, data$arr_delay))+
  geom_point(aes(shape= data$carrier,color=cluster))+   theme_bw()+ggtitle("3-means clustering via 2 features")
p5

km.out=kmeans(data[, 2:3],3,nstart=20)
data$cluster=factor(km.out$cluster)
p6 = ggplot(data,aes(data$air_time, data$distance))+
  geom_point(aes(shape= data$carrier,color=cluster))+   theme_bw()+ggtitle("3-means clustering via 2 features")
p6

km.out=kmeans(data[,c(2,4)],3,nstart=20)
data$cluster=factor(km.out$cluster)
p7 = ggplot(data,aes(data$air_time, data$arr_delay))+
  geom_point(aes(shape= data$carrier,color=cluster))+   theme_bw()+ggtitle("3-means clustering via 2 features")
p7

km.out=kmeans(data[, 3:4],3,nstart=20)
data$cluster=factor(km.out$cluster)
p8 = ggplot(data,aes(data$distance, data$arr_delay))+
  geom_point(aes(shape= data$carrier,color=cluster))+   theme_bw()+ggtitle("3-means clustering via 2 features")
p8
library(gridExtra); grid.arrange(p,p3,nrow=2)
```

```{R 3.1.4}

set.seed(1)

km.out=kmeans(data[,1:2],2,nstart=20)
data$cluster=factor(km.out$cluster)
ggplot(data,aes(data$dep_delay,data$air_time))+
  geom_point(aes(shape= data$month,color=cluster))+   theme_bw()+ggtitle("2-means clustering via 2 features")

km.out=kmeans(data[,c(1,3)],2,nstart=20)
data$cluster=factor(km.out$cluster)
ggplot(data,aes(data$dep_delay, data$distance))+
  geom_point(aes(shape= data$month,color=cluster))+   theme_bw()+ggtitle("2-means clustering via 2 features")

km.out=kmeans(data[,c(1,4)],2,nstart=20)
data$cluster=factor(km.out$cluster)
ggplot(data,aes(data$dep_delay, data$arr_delay))+
  geom_point(aes(shape= data$month,color=cluster))+   theme_bw()+ggtitle("2-means clustering via 2 features")

km.out=kmeans(data[, 2:3],2,nstart=20)
data$cluster=factor(km.out$cluster)
ggplot(data,aes(data$air_time, data$distance))+
  geom_point(aes(shape= data$month,color=cluster))+   theme_bw()+ggtitle("2-means clustering via 2 features")

km.out=kmeans(data[,c(2,4)],2,nstart=20)
data$cluster=factor(km.out$cluster)
ggplot(data,aes(data$air_time, data$arr_delay))+
  geom_point(aes(shape= data$month,color=cluster))+   theme_bw()+ggtitle("2-means clustering via 2 features")

km.out=kmeans(data[, 3:4],2,nstart=20)
data$cluster=factor(km.out$cluster)
ggplot(data,aes(data$distance, data$arr_delay))+
  geom_point(aes(shape= data$month,color=cluster))+   theme_bw()+ggtitle("2-means clustering via 2 features")


```

When looking at 3-means clustering via 4 features clusters, I used arrival delay and departure delay as the two features to track observations. When I did this, I realized the clusters the algorithm had created were overlapping. There were not three distinct clusters that were created. I thought this was interesting, so then I did 2-means clustering via 4 features for month, and I used arrival delay and departure delay for that as well. Since there were only 2 clusters, the plot wasn't as messy, but the clusters were still overlapping and there wasn't a clear separation of clusters. 
After finding overlapping clusters, I performed 3-means clustering via 2 features for carrier with other feature combinations.Clusters involving distance as a feature seemed to be the most distinct. There are a lot of points that are close to each other so it is difficult to assess, but it looks like a case could be made that 3-means via 2 features worked on separating into distinct clusters. An example of this would be the plot with arrival delay and distance. It looks like the majority of the points in the green cluster are carrier UA, the red cluster majority DL, and the blue cluster majority AA. Most of the plots involving the distance feature look like this, even when clustering by month. One cluster I thought that looked interesting when clustering by carrier was when the features were arrival delay and air time. You can't tell how distinct the clusters are, but it looks like the clusters are all moving toward a central point.
My finding were pretty similar when clustering by month. There are so many points, it is difficult to decipher the clusters. When looking at arrival delay and departure delay when clustering by month, it looks like there is a linear relationship between the two features, and the clusters are stretched linearly as well. In that particular plot, it looks like there are longer arrival and departure delays in the seventh moth of the year. Again, it is difficult to make out the points, but it also looks like in the plot with distance and departure delay clustered by month, in month 7 planes went a further distance than in month 2.



3.2) Use `set.seed(123)` to randomly extract 50 observations, and to these 50 observations, apply hierarchical clustering with average linkage. (i) Cut the dendrogram to obtain 3 clusters with leafs annotated by `carrier` names and resulting clusters colored distinctly, and report the corresponding height of cut. (ii) In addition, cut the dendrogram to obtain 2 clusters with leafs annotated by `month` numbers and resulting clusters colored distinctly, and report the corresponding height of cut. Here are some hints: say, you save the randomly extracted 50 observations into an object `ds3sd`, for these observations save their `carrier` names by keeping their object type but save `month` numbers as a `character` vector, make sure that `ds3sd` is a `matrix`, transpose `ds3sd` into `tmp`, assign to `tmp` column names with their corresponding carrier names or month numbers, and then transpose `tmp` and save it as `ds3sd`; this way, you are done assigning cluster labels to each observation in `ds3sd`; then you are ready to use the commands in the file `Plotggdendro.r` to create the desired dendrograms. 


The first two dendrograms are standardized

```{R 3.2}

set.seed(123)
ds3sd = sample(1:dim(data1)[1], size =50, replace = F)

tmp = data1[ds3sd, ]

ds3sd = tmp %>% select(carrier, month, arr_delay, dep_delay, distance, air_time)

distance = dist(scale(ds3sd[3:6]), method = "euclidean")

cluster = hclust(distance, method = "average")

clustdata = dendro_data_k(hc = cluster, k = 3)
height3 = sort(cluster$height)

clustdata$labels$label = paste(as.character(ds3sd$carrier), clustdata$labels$label, sep = " ")
source("Plotggdendro.r")
cutheight = height3[length(height3)-3]
plot_ggdendro(clustdata,
direction = "tb",heightReferece= cutheight,expand.y = 0.2)

cutheight

```

```{R 3.2.2}
set.seed(123)
distance = dist(scale(ds3sd[3:6]), method = "euclidean")

cluster = hclust(distance, method = "average")

clustdata = dendro_data_k(hc = cluster, k = 2)
height2 = sort(cluster$height)

clustdata$labels$label = paste(as.character(ds3sd$month), clustdata$labels$label, sep = " ")
source("Plotggdendro.r")
cutheight = height2[length(height2)-2]
plot_ggdendro(clustdata,
direction = "tb",heightReferece= cutheight,expand.y = 0.2)

cutheight

```

The last two dendrograms are not standardized.

```{R 3.2.3}
set.seed(123)
distance = dist((ds3sd[3:6]), method = "euclidean")

cluster = hclust(distance, method = "average")

clustdata = dendro_data_k(hc = cluster, k = 2)
height2 = sort(cluster$height)

clustdata$labels$label = paste(as.character(ds3sd$month), clustdata$labels$label, sep = " ")
source("Plotggdendro.r")
cutheight = height2[length(height2)-2]
plot_ggdendro(clustdata,
direction = "tb",heightReferece= cutheight,expand.y = 0.2)

cutheight
```


```{R 3.2.4}
set.seed(123)
distance = dist((ds3sd[3:6]), method = "euclidean")

cluster = hclust(distance, method = "average")

clustdata = dendro_data_k(hc = cluster, k = 3)
height3 = sort(cluster$height)

clustdata$labels$label = paste(as.character(ds3sd$carrier), clustdata$labels$label, sep = " ")
source("Plotggdendro.r")
cutheight = height3[length(height3)-3]
plot_ggdendro(clustdata,
direction = "tb",heightReferece= cutheight,expand.y = 0.2) 

cutheight

```